### ISSUE TITLE
java.lang.NoSuchMethodError: No interface method startReplaceableGroup(ILjava/lang/String;)V in class Landroidx/compose/runtime/Composer

### ISSUE THREAD

**Issue by tenSunFree** [ellisonchan/ComposeMovie#2]
java.lang.NoSuchMethodError: No interface method startReplaceableGroup(ILjava/lang/String;)V in class Landroidx/compose/runtime/Composer; or its super classes (declaration of 'androidx.compose.runtime.Composer' appears in /data/app/com.ellison.composemovie-ay3hzie4VwOnMmpEsYG9wA==/base.apk)
<img width="893" alt="2021-06-12_025246" src="https://user-images.githubusercontent.com/23090085/121736067-a35fe300-cb29-11eb-9ca7-9404b5919b1b.png">

My solution is to change kotlin_version to 1.4.32 and compose_version to 1.0.0-beta06
<img width="480" alt="2021-06-12_025749" src="https://user-images.githubusercontent.com/23090085/121736517-40bb1700-cb2a-11eb-96d2-2d24c8374120.png">

**Comment by ellisonchan** [comment]
Hello, tenSun.

Thank for your use.
U can fork and pull the fix to main brranch. I would merge it.
